/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments.index'
import { Route as TokenAppointmentIdRouteImport } from './routes/token.$appointmentId'
import { Route as OwnerQueueRouteImport } from './routes/owner.queue'
import { Route as OwnerLoginRouteImport } from './routes/owner.login'
import { Route as OwnerDoctorsRouteImport } from './routes/owner.doctors'
import { Route as BookSuccessRouteImport } from './routes/book.success'
import { Route as BookConfirmRouteImport } from './routes/book.confirm'
import { Route as AppointmentsIdRouteImport } from './routes/appointments.$id'
import { Route as BookClinicIdIndexRouteImport } from './routes/book.$clinicId.index'
import { Route as BookClinicIdDoctorIdRouteImport } from './routes/book.$clinicId.$doctorId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenAppointmentIdRoute = TokenAppointmentIdRouteImport.update({
  id: '/token/$appointmentId',
  path: '/token/$appointmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerQueueRoute = OwnerQueueRouteImport.update({
  id: '/owner/queue',
  path: '/owner/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner/login',
  path: '/owner/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDoctorsRoute = OwnerDoctorsRouteImport.update({
  id: '/owner/doctors',
  path: '/owner/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const BookSuccessRoute = BookSuccessRouteImport.update({
  id: '/book/success',
  path: '/book/success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmRoute = BookConfirmRouteImport.update({
  id: '/book/confirm',
  path: '/book/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/appointments/$id',
  path: '/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookClinicIdIndexRoute = BookClinicIdIndexRouteImport.update({
  id: '/book/$clinicId/',
  path: '/book/$clinicId/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookClinicIdDoctorIdRoute = BookClinicIdDoctorIdRouteImport.update({
  id: '/book/$clinicId/$doctorId',
  path: '/book/$clinicId/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/book/confirm': typeof BookConfirmRoute
  '/book/success': typeof BookSuccessRoute
  '/owner/doctors': typeof OwnerDoctorsRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/queue': typeof OwnerQueueRoute
  '/token/$appointmentId': typeof TokenAppointmentIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/book/': typeof BookIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/book/$clinicId/$doctorId': typeof BookClinicIdDoctorIdRoute
  '/book/$clinicId/': typeof BookClinicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/book/confirm': typeof BookConfirmRoute
  '/book/success': typeof BookSuccessRoute
  '/owner/doctors': typeof OwnerDoctorsRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/queue': typeof OwnerQueueRoute
  '/token/$appointmentId': typeof TokenAppointmentIdRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/book': typeof BookIndexRoute
  '/owner': typeof OwnerIndexRoute
  '/book/$clinicId/$doctorId': typeof BookClinicIdDoctorIdRoute
  '/book/$clinicId': typeof BookClinicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/book/confirm': typeof BookConfirmRoute
  '/book/success': typeof BookSuccessRoute
  '/owner/doctors': typeof OwnerDoctorsRoute
  '/owner/login': typeof OwnerLoginRoute
  '/owner/queue': typeof OwnerQueueRoute
  '/token/$appointmentId': typeof TokenAppointmentIdRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/book/': typeof BookIndexRoute
  '/owner/': typeof OwnerIndexRoute
  '/book/$clinicId/$doctorId': typeof BookClinicIdDoctorIdRoute
  '/book/$clinicId/': typeof BookClinicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/appointments/$id'
    | '/book/confirm'
    | '/book/success'
    | '/owner/doctors'
    | '/owner/login'
    | '/owner/queue'
    | '/token/$appointmentId'
    | '/appointments/'
    | '/book/'
    | '/owner/'
    | '/book/$clinicId/$doctorId'
    | '/book/$clinicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/appointments/$id'
    | '/book/confirm'
    | '/book/success'
    | '/owner/doctors'
    | '/owner/login'
    | '/owner/queue'
    | '/token/$appointmentId'
    | '/appointments'
    | '/book'
    | '/owner'
    | '/book/$clinicId/$doctorId'
    | '/book/$clinicId'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/profile'
    | '/appointments/$id'
    | '/book/confirm'
    | '/book/success'
    | '/owner/doctors'
    | '/owner/login'
    | '/owner/queue'
    | '/token/$appointmentId'
    | '/appointments/'
    | '/book/'
    | '/owner/'
    | '/book/$clinicId/$doctorId'
    | '/book/$clinicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  AppointmentsIdRoute: typeof AppointmentsIdRoute
  BookConfirmRoute: typeof BookConfirmRoute
  BookSuccessRoute: typeof BookSuccessRoute
  OwnerDoctorsRoute: typeof OwnerDoctorsRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  OwnerQueueRoute: typeof OwnerQueueRoute
  TokenAppointmentIdRoute: typeof TokenAppointmentIdRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  BookIndexRoute: typeof BookIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  BookClinicIdDoctorIdRoute: typeof BookClinicIdDoctorIdRoute
  BookClinicIdIndexRoute: typeof BookClinicIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$appointmentId': {
      id: '/token/$appointmentId'
      path: '/token/$appointmentId'
      fullPath: '/token/$appointmentId'
      preLoaderRoute: typeof TokenAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/queue': {
      id: '/owner/queue'
      path: '/owner/queue'
      fullPath: '/owner/queue'
      preLoaderRoute: typeof OwnerQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/login': {
      id: '/owner/login'
      path: '/owner/login'
      fullPath: '/owner/login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/doctors': {
      id: '/owner/doctors'
      path: '/owner/doctors'
      fullPath: '/owner/doctors'
      preLoaderRoute: typeof OwnerDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/success': {
      id: '/book/success'
      path: '/book/success'
      fullPath: '/book/success'
      preLoaderRoute: typeof BookSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirm': {
      id: '/book/confirm'
      path: '/book/confirm'
      fullPath: '/book/confirm'
      preLoaderRoute: typeof BookConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/appointments/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$clinicId/': {
      id: '/book/$clinicId/'
      path: '/book/$clinicId'
      fullPath: '/book/$clinicId/'
      preLoaderRoute: typeof BookClinicIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$clinicId/$doctorId': {
      id: '/book/$clinicId/$doctorId'
      path: '/book/$clinicId/$doctorId'
      fullPath: '/book/$clinicId/$doctorId'
      preLoaderRoute: typeof BookClinicIdDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  AppointmentsIdRoute: AppointmentsIdRoute,
  BookConfirmRoute: BookConfirmRoute,
  BookSuccessRoute: BookSuccessRoute,
  OwnerDoctorsRoute: OwnerDoctorsRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  OwnerQueueRoute: OwnerQueueRoute,
  TokenAppointmentIdRoute: TokenAppointmentIdRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  BookIndexRoute: BookIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  BookClinicIdDoctorIdRoute: BookClinicIdDoctorIdRoute,
  BookClinicIdIndexRoute: BookClinicIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
